### PR TITLE
Correct disasm

### PR DESCRIPTION
**Pull request by badboy**
Debugging my own BPF programs I noticed a wrong output in the disassembler.
This fixes it, see the first two commits.

I added tests for the disassembler output by roundtripping through the assembler (so it's easier to write). I more or less took all assembler tests, only removed the error-case ones and some which used shortened instructions (`add` instead of `add64`). This testing is not perfect, but should catch a mismatch here.

### CODE REVIEW

**Comment by qmonnet** [comment]
Good catch, thanks! The `imm` <-> `off` confusion is a stupid mistake of mine, and it seems I missed the difference for load and store at the time I wrote the disassembler. Thanks!

I'll review the tests this weekend. I saw Rich's copyright in the file boilerplate, did you reuse tests from uBPF?

**Comment by badboy** [comment]
Oops, I actually just copied over `test/assembler.rs`. I can remove that statement

**Comment by qmonnet** [comment]
Yeah, well, probably better add your own copyright instead :-)

**Comment by badboy** [comment]
Will do

**Comment by badboy** [comment]
Changed the copyright

**Comment by qmonnet** [comment]
Tests are fine as well, thanks for that. Thanks for the fix. Thanks for the PR. Thanks for everything! Merging now.

**Pull request merged**
